### PR TITLE
fix: avoid issues finding node binary on mac

### PR DESCRIPTION
**Pull request by eliias**

### CODE REVIEW

**Comment by keithamus** [comment]
:+1:

**Comment by cesarandreu** [comment]
Can we a get release? It seems it got removed originally in this PR: https://github.com/keithamus/parallelshell/commit/1628a1495203e5bb2cd895a83528f628b9722d08

Now it's not working for me on OSX. This change should fix it.

**Comment by keithamus** [comment]
Ahh, so it did. My bad. I'll release.

**Comment by cesarandreu** [comment]
Thanks for the quick fix @keithamus :+1:

**Pull request merged**
