### PR TITLE
remove unneeded comma

### PR DESCRIPTION
**Pull request by jannavratil**

### CODE REVIEW

**Comment by keithamus** [comment]
I like that comma. He's my best friend. Why do you want to get rid of him?

**Comment by jannavratil** [comment]
Because for me it's like "PHP code style" and in normal web JavaScript is comma not welcome in and of array/object. But you are Owner of project, so I'll be respect your friendships.

**Comment by keithamus** [comment]
I appreciate your comment @jannavratil, and I appreciate you taking the time to make a PR and try to make this project better. Having said that I have two points to make:

1. This is not normal web JavaScript, this is node.js. It is ES5 compliant and trailing commas are welcome (see http://es5.github.io/#x11.1.4 and http://es5.github.io/#x11.1.5)
2. It is easier for diffs if all objects end in comma, as if I were to add a property to the object, if every line has a trailing comma it would result in a 1 line diff. If the last line did not have a trailing comma it would result in a 3 line diff.

**Comment by jannavratil** [comment]
Thanks for your time and great explanation. I'm not using node.js on daily basis so sorry for wasting your time and for me is maybe good time to change IDE settings or habits :)

**Comment by keithamus** [comment]
Was not a waste of time, always good to have your code questioned :smile:

**Pull request closed without merging**
